sudo: required

services:
  - docker

script:
- DOCKER_TAG=travisci make -f Makefile.docker image
# make sure image can run
- docker run -e LOG_TO_SYSLOG=0 -v /var/run/docker.sock:/var/run/docker.sock spotify/docker-gc:travisci
